export interface Pokemon {
    _id?: string; // This will map to MongoDB's ObjectId (_id), optional in case it's generated by the backend.
    name: string;
    type: string[]; // Array of types.
    base: {
      HP: number;
      Attack: number;
      Defense: number;
      Speed: number;
    };
    evolution: {
      prev: string | null; // References another Pokemon by its ID.
      next: string[]; // Array of IDs for the next evolutions.
    };
    generation: number;
    legendary: boolean;
    image: string; // URL for the Pokémon's image.
    img?: string;
}
